services:
  cookie:
    build:
      context: ./cookie-fetcher
      dockerfile: Dockerfile
    ports: ["8041:8041"]
    shm_size: '1gb'
    restart: unless-stopped

  backend:
    shm_size: '1gb'
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports: ["8080:8080"]
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: ["80:3000", "3000:3000"]
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:16
    restart: unless-stopped
    ports: ["5432:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: