export const COURT_OPTIONS = [
  { label: 'Верховный Суд РФ', value: 'VS' },
  { label: 'Высший Арбитражный Суд РФ', value: 'VAS' },
  { label: 'АС Волго-Вятского округа', value: 'FASVVO' },
  { label: 'АС Восточно-Сибирского округа', value: 'FASVSO' },
  { label: 'АС Дальневосточного округа', value: 'FASDVO' },
  { label: 'АС Западно-Сибирского округа', value: 'FASZSO' },
  { label: 'АС Московского округа', value: 'FASMO' },
  { label: 'АС Поволжского округа', value: 'FASPO' },
  { label: 'АС Северо-Западного округа', value: 'FASSZO' },
  { label: 'АС Северо-Кавказского округа', value: 'FASSKO' },
  { label: 'АС Уральского округа', value: 'FASUO' },
  { label: 'АС Центрального округа', value: 'FASCO' },
  { label: '1 арбитражный апелляционный суд', value: '1AAS' },
  { label: '2 арбитражный апелляционный суд', value: '2AAS' },
  { label: '3 арбитражный апелляционный суд', value: '3AAS' },
  { label: '4 арбитражный апелляционный суд', value: '4AAS' },
  { label: '5 арбитражный апелляционный суд', value: '5AAS' },
  { label: '6 арбитражный апелляционный суд', value: '6AAS' },
  { label: '7 арбитражный апелляционный суд', value: '7AAS' },
  { label: '8 арбитражный апелляционный суд', value: '8AAS' },
  { label: '9 арбитражный апелляционный суд', value: '9AAS' },
  { label: '10 арбитражный апелляционный суд', value: '10AAS' },
  { label: '11 арбитражный апелляционный суд', value: '11AAS' },
  { label: '12 арбитражный апелляционный суд', value: '12AAS' },
  { label: '13 арбитражный апелляционный суд', value: '13AAS' },
  { label: '14 арбитражный апелляционный суд', value: '14AAS' },
  { label: '15 арбитражный апелляционный суд', value: '15AAS' },
  { label: '16 арбитражный апелляционный суд', value: '16AAS' },
  { label: '17 арбитражный апелляционный суд', value: '17AAS' },
  { label: '18 арбитражный апелляционный суд', value: '18AAS' },
  { label: '19 арбитражный апелляционный суд', value: '19AAS' },
  { label: '20 арбитражный апелляционный суд', value: '20AAS' },
  { label: '21 арбитражный апелляционный суд', value: '21AAS' },
  { label: 'АС Алтайского края', value: 'ALTAI-KRAI' },
  { label: 'АС Амурской области', value: 'AMURAS' },
  { label: 'АС Архангельской области', value: 'ARHANGELSK' },
  { label: 'АС Астраханской области', value: 'ASTRAHAN' },
  { label: 'АС Белгородской области', value: 'BELGOROD' },
  { label: 'АС Брянской области', value: 'BRYANSK' },
  { label: 'АС Владимирской области', value: 'VLADIMIR' },
  { label: 'АС Волгоградской области', value: 'VOLGOGRAD' },
  { label: 'АС Вологодской области', value: 'VOLOGDA' },
  { label: 'АС Воронежской области', value: 'VORONEJ' },
  { label: 'АС города Москвы', value: 'MSK' },
  { label: 'АС города Санкт-Петербурга и Ленинградской области', value: 'SPB' },
  { label: 'АС города Севастополя', value: 'SEVASTOPOL' },
  { label: 'АС Донецкой Народной Республики', value: 'DNR' },
  { label: 'АС Еврейской автономной области', value: 'EAO' },
  { label: 'АС Забайкальского края', value: 'CHITA' },
  { label: 'АС Запорожской области', value: 'ZAPOROZHYE' },
  { label: 'АС Ивановской области', value: 'IVANOVO' },
  { label: 'АС Иркутской области', value: 'IRKUTSK' },
  { label: 'АС Кабардино-Балкарской Республики', value: 'ASKB' },
  { label: 'АС Калининградской области', value: 'KALININGRAD' },
  { label: 'АС Калужской области', value: 'KALUGA' },
  { label: 'АС Камчатского края', value: 'KAMCHATKA' },
  { label: 'АС Карачаево-Черкесской Республики', value: 'ASKCHR' },
  { label: 'АС Кемеровской области', value: 'KEMEROVO' },
  { label: 'АС Кировской области', value: 'KIROV' },
  { label: 'АС Коми-Пермяцкого АО', value: 'KOMI-PERM' },
  { label: 'АС Костромской области', value: 'KOSTROMA' },
  { label: 'АС Краснодарского края', value: 'KRASNODAR' },
  { label: 'АС Красноярского края', value: 'KRANSOYARSK' },
  { label: 'АС Курганской области', value: 'KURGAN' },
  { label: 'АС Курской области', value: 'KURSK' },
  { label: 'АС Липецкой области', value: 'LIPETSK' },
  { label: 'АС Луганской Народной Республики', value: 'LNR' },
  { label: 'АС Магаданской области', value: 'MAGADAN' },
  { label: 'АС Московской области', value: 'ASMO' },
  { label: 'АС Мурманской области', value: 'MURMANSK' },
  { label: 'АС Нижегородской области', value: 'NNOV' },
  { label: 'АС Новгородской области', value: 'NOVGOROD' },
  { label: 'АС Новосибирской области', value: 'NOVOSIB' },
  { label: 'АС Омской области', value: 'OMSK' },
  { label: 'АС Оренбургской области', value: 'ORENBURG' },
  { label: 'АС Орловской области', value: 'OREL' },
  { label: 'АС Пензенской области', value: 'PENZA' },
  { label: 'АС Пермского края', value: 'PERM' },
  { label: 'АС Приморского края', value: 'PRIMKRAY' },
  { label: 'АС Псковской области', value: 'PSKOV' },
  { label: 'АС Республики Адыгея', value: 'ADYG' },
  { label: 'АС Республики Алтай', value: 'ALTAI' },
  { label: 'АС Республики Башкортостан', value: 'UFA' },
  { label: 'АС Республики Бурятия', value: 'BURYATIA' },
  { label: 'АС Республики Дагестан', value: 'MAHACHKALA' },
  { label: 'АС Республики Ингушетия', value: 'INGUSHETIA' },
  { label: 'АС Республики Калмыкия', value: 'KALMYK' },
  { label: 'АС Республики Карелия', value: 'KARELIA' },
  { label: 'АС Республики Коми', value: 'KOMI' },
  { label: 'АС Республики Крым', value: 'KRYM' },
  { label: 'АС Республики Марий Эл', value: 'MARI-EL' },
  { label: 'АС Республики Мордовия', value: 'ASRM' },
  { label: 'АС Республики Саха', value: 'YAKUTSK' },
  { label: 'АС Республики Северная Осетия', value: 'ALANIA' },
  { label: 'АС Республики Татарстан', value: 'TATARSTAN' },
  { label: 'АС Республики Тыва', value: 'TYVA' },
  { label: 'АС Республики Хакасия', value: 'KHAKASIA' },
  { label: 'АС Ростовской области', value: 'ROSTOV' },
  { label: 'АС Рязанской области', value: 'RYAZAN' },
  { label: 'АС Самарской области', value: 'SAMARA' },
  { label: 'АС Саратовской области', value: 'SARATOV' },
  { label: 'АС Сахалинской области', value: 'SAKHALIN' },
  { label: 'АС Свердловской области', value: 'EKATERINBURG' },
  { label: 'АС Смоленской области', value: 'SMOLENSK' },
  { label: 'АС Ставропольского края', value: 'STAVROPOL' },
  { label: 'АС Тамбовской области', value: 'TAMBOV' },
  { label: 'АС Тверской области', value: 'TVER' },
  { label: 'АС Томской области', value: 'TOMSK' },
  { label: 'АС Тульской области', value: 'TULA' },
  { label: 'АС Тюменской области', value: 'TUMEN' },
  { label: 'АС Удмуртской Республики', value: 'UDMURTIYA' },
  { label: 'АС Ульяновской области', value: 'ULYANOVSK' },
  { label: 'АС Хабаровского края', value: 'KHABAROVSK' },
  { label: 'АС Ханты-Мансийского АО', value: 'HMAO' },
  { label: 'АС Херсонской области', value: 'KHERSON' },
  { label: 'АС Челябинской области', value: 'CHEL' },
  { label: 'АС Чеченской Республики', value: 'CHECHNYA' },
  { label: 'АС Чувашской Республики', value: 'CHUVASHIA' },
  { label: 'АС Чукотского АО', value: 'CHUKOTKA' },
  { label: 'АС Ямало-Ненецкого АО', value: 'YAMAL' },
  { label: 'АС Ярославской области', value: 'YAROSLAVL' },
  { label: 'ПСП Арбитражного суда Пермского края', value: 'KUDIMKAR' },
  { label: 'ПСП Арбитражный суд Архангельской области', value: 'NARYANMAR' },
  { label: 'Суд по интеллектуальным правам', value: 'SIP' },
];